services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - apisix-network
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/bitnami/etcd
    restart: always

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    networks:
      - apisix-network
    ports:
      - "80:80"
      - "9180:9180"
    restart: always

  dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix_dashboard
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
    environment:
      - DASHBOARD_ADMIN_API=http://apisix:9180
      - DASHBOARD_API_KEY=admin
      - DASHBOARD_API_SECRET=admin
    networks:
      - apisix-network
    ports:
      - "9000:9000"

volumes:
  etcd-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/etcd-data
      o: bind

networks:
  apisix-network:
    driver: bridge